version: "3"
services:
  db:
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata

  web:
    volumes:
      - ./backend/app:/app
      - ./backend/assets:/assets
    build:
      dockerfile: Dockerfile-dev

  frontend:
    build:
      dockerfile: Dockerfile-dev
    volumes:
      - ./frontend/jksa-app:/app
      - /app/node_modules
    ports:
      - "3000:3000"

volumes:
  app-db-data:
