version: "3"
services:
  db:
    image: postgres:14  # https://hub.docker.com/_/postgres
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata

  web:
    volumes:
      - ./backend/app:/app
      - ./backend/assets:/assets

volumes:
  app-db-data:
